name: Python Broadcast Image Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Install MySQL client
      - name: Install MySQL client
        run: sudo apt-get install -y mysql-client

      - name: Start MySQL Service
        run: |
            sudo apt-get update
            sudo apt-get install -y mysql-server
            sudo systemctl start mysql

      - name: Check MySQL Service
        run: sudo systemctl status mysql

      - name: Set up database and user
        run: |
          sudo mysql -u root -e "SHOW DATABASES;"
          sudo mysql -u root -e "CREATE DATABASE broadcast;"
          sudo mysql -u root -e "CREATE USER 'admin'@'localhost' IDENTIFIED BY 'admin';"
          sudo mysql -u root -e "GRANT ALL PRIVILEGES ON broadcast.* TO 'admin'@'localhost';"
          sudo mysql -u root -e "FLUSH PRIVILEGES;"

      - name: Add test data to database
        run:
          sudo mysql -u root -e "USE broadcast; CREATE TABLE IF NOT EXISTS users (id INT AUTO_INCREMENT PRIMARY KEY, chatid BIGINT, status_bc TINYINT DEFAULT 0 NOT NULL);"
          sudo mysql -u root -e "USE broadcast; INSERT INTO users (chatid) VALUES (5228446974), (5228446974);"
      
      - name: Set up virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt

      # Configure MySQL connection (if using an external MySQL server)
    #   - name: Set up database configuration
    #     env:
    #       DB_HOST: 127.0.0.1
    #       DB_PORT: 3306
    #       DB_USER: admin
    #       DB_PASSWORD: admin
    #       DB_NAME: broadcast
    #     run: |
    #       echo "MySQL database at $DB_HOST:$DB_PORT"
    #       source venv/bin/activate
    #       python setup_database.py  

      # Run Python broadcast script
      - name: Run broadcast script
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_USER: admin
          DB_PASSWORD: admin
          DB_NAME: broadcast
        run: |
          source venv/bin/activate
          python main.py 

